# Kubectl aliases – mirrors the OMZ kubectl plugin.

alias k='kubectl'

# ── Apply ─────────────────────────────────────────────────────────────────────
alias kaf='kubectl apply -f'
alias kapk='kubectl apply -k'

# ── Config / Context ──────────────────────────────────────────────────────────
alias kccc='kubectl config current-context'
alias kcdc='kubectl config delete-context'
alias kcgc='kubectl config get-contexts'
alias kcn='kubectl config set-context --current --namespace'
alias kcsc='kubectl config set-context'
alias kcuc='kubectl config use-context'

# ── Copy ──────────────────────────────────────────────────────────────────────
alias kcp='kubectl cp'

# ── Delete ────────────────────────────────────────────────────────────────────
alias kdel='kubectl delete'
alias kdelf='kubectl delete -f'
alias kdelk='kubectl delete -k'
alias kdelcj='kubectl delete cronjob'
alias kdelcm='kubectl delete configmap'
alias kdeld='kubectl delete deployment'
alias kdelds='kubectl delete daemonset'
alias kdeli='kubectl delete ingress'
alias kdelj='kubectl delete job'
alias kdelno='kubectl delete node'
alias kdelns='kubectl delete namespace'
alias kdelp='kubectl delete pods'
alias kdelpvc='kubectl delete pvc'
alias kdelsa='kubectl delete sa'
alias kdelsec='kubectl delete secret'
alias kdels='kubectl delete svc'
alias kdelss='kubectl delete statefulset'

# ── Describe ──────────────────────────────────────────────────────────────────
alias kdcj='kubectl describe cronjob'
alias kdcm='kubectl describe configmap'
alias kdd='kubectl describe deployment'
alias kdds='kubectl describe daemonset'
alias kdi='kubectl describe ingress'
alias kdj='kubectl describe job'
alias kdno='kubectl describe node'
alias kdns='kubectl describe namespace'
alias kdp='kubectl describe pods'
alias kdpvc='kubectl describe pvc'
alias kdrs='kubectl describe replicaset'
alias kdsa='kubectl describe sa'
alias kdsec='kubectl describe secret'
alias kds='kubectl describe svc'
alias kdss='kubectl describe statefulset'

# ── Edit ──────────────────────────────────────────────────────────────────────
alias kecj='kubectl edit cronjob'
alias kecm='kubectl edit configmap'
alias ked='kubectl edit deployment'
alias keds='kubectl edit daemonset'
alias kei='kubectl edit ingress'
alias kej='kubectl edit job'
alias keno='kubectl edit node'
alias kens='kubectl edit namespace'
alias kep='kubectl edit pods'
alias kepvc='kubectl edit pvc'
alias kers='kubectl edit replicaset'
alias kes='kubectl edit svc'
alias kess='kubectl edit statefulset'

# ── Exec ──────────────────────────────────────────────────────────────────────
alias keti='kubectl exec -t -i'

# ── Get ───────────────────────────────────────────────────────────────────────
alias kga='kubectl get all'
alias kgaa='kubectl get all --all-namespaces'
alias kgcj='kubectl get cronjob'
alias kgcm='kubectl get configmaps'
alias kgcma='kubectl get configmaps --all-namespaces'
alias kgd='kubectl get deployment'
alias kgda='kubectl get deployment --all-namespaces'
alias kgdw='kgd --watch'
alias kgdwide='kgd -o wide'
alias kgds='kubectl get daemonset'
alias kgdsa='kubectl get daemonset --all-namespaces'
alias kgdsw='kgds --watch'
alias kge='kubectl get events --sort-by=".lastTimestamp"'
alias kgew='kubectl get events --sort-by=".lastTimestamp" --watch'
alias kgi='kubectl get ingress'
alias kgia='kubectl get ingress --all-namespaces'
alias kgj='kubectl get job'
alias kgno='kubectl get nodes'
alias kgnosl='kubectl get nodes --show-labels'
alias kgns='kubectl get namespaces'
alias kgp='kubectl get pods'
alias kgpa='kubectl get pods --all-namespaces'
alias kgpall='kubectl get pods --all-namespaces -o wide'
alias kgpl='kgp -l'
alias kgpn='kgp -n'
alias kgpsl='kubectl get pods --show-labels'
alias kgpvc='kubectl get pvc'
alias kgpvca='kubectl get pvc --all-namespaces'
alias kgpvcw='kgpvc --watch'
alias kgpw='kgp --watch'
alias kgpwide='kgp -o wide'
alias kgrs='kubectl get replicaset'
alias kgs='kubectl get svc'
alias kgsa='kubectl get svc --all-namespaces'
alias kgsec='kubectl get secret'
alias kgseca='kubectl get secret --all-namespaces'
alias kgss='kubectl get statefulset'
alias kgssa='kubectl get statefulset --all-namespaces'
alias kgssw='kgss --watch'
alias kgsswide='kgss -o wide'
alias kgsw='kgs --watch'
alias kgswide='kgs -o wide'
alias kca='kubectl get all --all-namespaces'

# ── Logs ──────────────────────────────────────────────────────────────────────
alias kl='kubectl logs'
alias klf='kubectl logs -f'
alias kl1h='kubectl logs --since 1h'
alias kl1m='kubectl logs --since 1m'
alias kl1s='kubectl logs --since 1s'
alias klf1h='kubectl logs --since 1h -f'
alias klf1m='kubectl logs --since 1m -f'
alias klf1s='kubectl logs --since 1s -f'

# ── Port-forward ──────────────────────────────────────────────────────────────
alias kpf='kubectl port-forward'

# ── Rollout ───────────────────────────────────────────────────────────────────
alias krh='kubectl rollout history'
alias krrd='kubectl rollout restart deployment'
alias krrss='kubectl rollout restart statefulset'
alias krsd='kubectl rollout status deployment'
alias krsss='kubectl rollout status statefulset'
alias kru='kubectl rollout undo'

# ── Scale ─────────────────────────────────────────────────────────────────────
alias ksd='kubectl scale deployment'
alias ksss='kubectl scale statefulset'
